[package]
name = "strtok"
version = "0.1.0"
authors = ["Victor I. Afolabi <vafolabi@lotlinx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "strtok"
path = "src/main.rs"

[dependencies]
